name: Deploy Main Site 

on: 
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy repository contents to remote server via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ vars.DILOOP_HOST }}
        username: ${{ vars.DILOOP_USER_NAME }}
        port: ${{ vars.DILOOP_PORT }}
        key: ${{ secrets.DILOOPSERVERKEY }}
        source: "."
        target: ${{ vars.DILOOP_TARGET_DIR }}

    - name: Executing remote command via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.DILOOP_HOST }}
        username: ${{ vars.DILOOP_USER_NAME }}
        port: ${{ vars.DILOOP_PORT }}
        key: ${{ secrets.DILOOPSERVERKEY }}
        script: |
              cd ${{vars.DILOOP_TARGET_DIR}}
              pnpm install  
              pnpm build
              pm2 restart reactdiloop
